In [2]:
import pandas as pd
import pathlib

# 데이터 파일 경로 지정
root = pathlib.Path.cwd().parent.parent.parent
file_path       = root / "storage" / "raw" / "recipe" / "recipe.csv"
new_file_path   = root / "storage" / "processed" / "recipe" / "recipe_fix.csv" 

print(root)
print(new_file_path)

c:\dev\project\SKN27-FINAL-1Team
c:\dev\project\SKN27-FINAL-1Team\storage\processed\recipe\recipe_fix.csv

In [3]:
# 1차 수정된 파일 로드 
df = pd.read_csv(new_file_path)
df.head(1)

,RCP_SNO,CKG_NM,INQ_CNT,SRAP_CNT,CKG_MTH_ACTO_NM,CKG_STA_ACTO_NM,CKG_MTRL_ACTO_NM,CKG_KND_ACTO_NM,CKG_MTRL_CN,CKG_INBUN_NM,CKG_DODF_NM,CKG_TIME_NM,INQ_CNT_RATE
0,7037475,김장김치,60777,52,절임,일상,채소류,김치/젓갈/장류,"['절임배추_20_kg_(1상자 7~9포기)', ' 무_1_개_(1600g 채썰때 ...",6인분이상,중급,2시간이내,1.0

In [4]:
# 조리법 개수 확인 
count = df["CKG_MTH_ACTO_NM"].nunique()
lst = df["CKG_MTH_ACTO_NM"].unique()

print(count)
print(lst)

## 확인 시 nan 케이스는 1껀 확인 (중복 제거 기준으로)
## 해당 레시피가 유니크 해서 제거해도 괜찮을 것으로 보임

14
['절임' '끓이기' '기타' '조림' '찜' '무침' '삶기' '볶음' '부침' '비빔' '굽기' '데치기' '튀김' '회' nan]

In [5]:
# 상황 개수 확인 
count = df["CKG_STA_ACTO_NM"].nunique()
lst = df["CKG_STA_ACTO_NM"].unique()

print(count)
print(lst)

## nan 55개 
## 상황 특정 안되어 있는 종류 하나로 규격화 하기 힘듬

13
['일상' '기타' '다이어트' '초스피드' '손님접대' '간식' '술안주' '야식' '명절' '영양식' nan '도시락' '해장'
 '이유식']

In [6]:
# 음식 분류 확인 
count = df["CKG_MTRL_ACTO_NM"].nunique()
lst = df["CKG_MTRL_ACTO_NM"].unique()

print(count)
print(lst)

## 결측치 없음 
## 유의미 하지 않은 필터가 있으면 제거 검토 
## 기타 컬럼의 개수가 좀 많음

16
['채소류' '닭고기' '기타' '과일류' '콩/견과류' '돼지고기' '가공식품류' '건어물류' '밀가루' '소고기' '곡류'
 '버섯류' '해물류' '달걀/유제품' '쌀' '육류']

In [7]:
# 음식 상세 분류 확인 
count = df["CKG_KND_ACTO_NM"].nunique()
lst = df["CKG_KND_ACTO_NM"].unique()

print(count)
print(lst)

## 결측치 없음 
## 유의미 하지 않은 필터가 있으면 제거 검토 
## 기타 컬럼의 개수가 좀 많음

17
['김치/젓갈/장류' '메인반찬' '밑반찬' '밥/죽/떡' '차/음료/술' '찌개' '국/탕' '양식' '면/만두' '양념/소스/잼'
 '과자' '기타' '디저트' '스프' '퓨전' '샐러드' '빵']

In [8]:
df.head(1)

,RCP_SNO,CKG_NM,INQ_CNT,SRAP_CNT,CKG_MTH_ACTO_NM,CKG_STA_ACTO_NM,CKG_MTRL_ACTO_NM,CKG_KND_ACTO_NM,CKG_MTRL_CN,CKG_INBUN_NM,CKG_DODF_NM,CKG_TIME_NM,INQ_CNT_RATE
0,7037475,김장김치,60777,52,절임,일상,채소류,김치/젓갈/장류,"['절임배추_20_kg_(1상자 7~9포기)', ' 무_1_개_(1600g 채썰때 ...",6인분이상,중급,2시간이내,1.0

In [9]:
# 분량 확인 
count = df["CKG_INBUN_NM"].nunique()
lst = df["CKG_INBUN_NM"].unique()

print(count)
print(lst)

## 인분 숫자를 조정해야 함 
## 6인분 이상에 대한 처리 
## nan에 대한 처리
## 모든 숫자를 1인분 기준으로 나눠서 처리할건지

6
['6인분이상' '2인분' '1인분' nan '3인분' '4인분' '5인분']

In [10]:
# 난이도 확인 
count = df["CKG_DODF_NM"].nunique()
lst = df["CKG_DODF_NM"].unique()

print(count)
print(lst)

## 난이도 분류를 믿을수는 없긴 함 
## 데이터가 빠진건 아니니 활용 자체는 검토 
## 아무나의 기준 확인 필요 (추가 분류 필요할 수 있음)

4
['중급' '아무나' '초급' '고급']

In [11]:
# 조리 시간 
count = df["CKG_TIME_NM"].nunique()
lst = df["CKG_TIME_NM"].unique()

print(count)
print(lst)

## 시간 기준은 모두 분 단위로 환산해서 처리 
## 해당 분 이하로 처리한다. 
## ex) 15면 0 ~ 15라는 뜻임 , 30이면 15 ~ 30이다. 
## 2시간 이상인 경우 어떻게 할지

8
['2시간이내' '60분이내' '2시간이상' '30분이내' nan '10분이내' '15분이내' '5분이내' '90분이내']

## 추가 컬럼 기준 분석

In [22]:
# 조회수 비율 5% 미만 데이터만 
df_viewrate = df[df["INQ_CNT_RATE"] > 0.015]
count = len(df_viewrate["INQ_CNT_RATE"])
print(count)

df_viewrate.head(10)

3293

,RCP_SNO,CKG_NM,INQ_CNT,SRAP_CNT,CKG_MTH_ACTO_NM,CKG_STA_ACTO_NM,CKG_MTRL_ACTO_NM,CKG_KND_ACTO_NM,CKG_MTRL_CN,CKG_INBUN_NM,CKG_DODF_NM,CKG_TIME_NM,INQ_CNT_RATE
0,7037475,김장김치,60777,52,절임,일상,채소류,김치/젓갈/장류,"['절임배추_20_kg_(1상자 7~9포기)', ' 무_1_개_(1600g 채썰때 ...",6인분이상,중급,2시간이내,1.000000
1,7022686,국물닭볶음탕,45495,35,끓이기,일상,닭고기,메인반찬,"['절단 닭_1_kg_', ' 대파_1_대_', ' 양파_1/2_개_', ' 당근_...",2인분,아무나,60분이내,0.748556
2,7031356,삭힌고추무침,38540,214,절임,일상,채소류,밑반찬,"['청양고추_500_g_', ' 굵은소금_50_ml_(3t듬쁙)', ' 설탕_100...",6인분이상,아무나,2시간이상,0.634121
3,7020066,국물떡볶이,37168,23,끓이기,일상,기타,밥/죽/떡,"['떡볶이 떡_150_g_', ' 사각 어묵 2장_120_g_', ' 양배추_55_...",1인분,아무나,30분이내,0.611547
4,7022132,레몬수,35210,64,기타,기타,과일류,차/음료/술,"['레몬___', ' 베이킹소다___', ' 식초___', ' 굵은소금___']",NaN,아무나,NaN,0.579331
5,7021550,고등어무조림,34821,230,조림,일상,기타,메인반찬,"['고등어_2_마리_(450g)', ' 무_500_g_', ' 양파_1_개_(190...",2인분,아무나,60분이내,0.572931
6,7018013,김치청국장,34723,2,끓이기,일상,콩/견과류,찌개,"['청국장_1_개_', ' 된장_1_스푼_', ' 소고기_80_g_', ' 양파_1...",NaN,초급,30분이내,0.571318
7,7020351,돼지고기수육,31764,12,찜,일상,돼지고기,메인반찬,"['돼지고기 앞다리살_1.2_kg_', ' 된장_2_스푼_', ' 미림_2_스푼_'...",NaN,아무나,NaN,0.522632
8,7019190,순두부찌개,31664,131,끓이기,일상,돼지고기,찌개,"['돼지고기 다짐육_150_g_', ' 순두부_1_개_', ' 양파_1/2_개_',...",2인분,아무나,30분이내,0.520987
9,7028673,오이냉국,29115,8,기타,일상,채소류,국/탕,"['오이_1_개_', ' 미역_170_g_(불린무게)', ' 홍고추_1_개_(생략가...",3인분,아무나,10분이내,0.479046